name: ci/cd

on:
  push:
    branches:
      - "main"

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: docker build images
      run: |
        docker build ./picture_api -t root0877/picture_api:$IMAGE_TAG 
        docker build ./image_miner -t root0877/image_miner:$IMAGE_TAG 
        docker build ./nginx -t root0877/miner_reverseproxy:$IMAGE_TAG 
        

    - name: docker push
      run: |
        docker push root0877/picture_api:$IMAGE_TAG
        docker push root0877/image_miner:$IMAGE_TAG
        docker push root0877/miner_reverseproxy:$IMAGE_TAG

